import type { Metadata } from 'next'

import { Toaster } from '@/components/ui/sonner'
import { Header } from '@/components/header'
import { ReactQueryProvider } from '@/utils/providers/react-query-provider'

export const metadata: Metadata = {
  title: 'Home | Photography',
  description: 'Generated by create next app',
}

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ReactQueryProvider>
      <div className="mx-auto max-w-5xl">
        <Header />
        <main className="mx-auto flex max-w-3xl flex-col items-center justify-center pb-12 pt-8">
          {children}
          <Toaster richColors />
        </main>
      </div>
    </ReactQueryProvider>
  )
}
